### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by theRealScoobaSteve** [manyuanrong/dso#11]
What are your future plans with this project? Do you plan on continuing to maintain this in the future?

**Comment by manyuanrong** [comment]
A closer goal is to adapt to multiple database drivers. Other needs to be prioritized based on feature requests

**Comment by theRealScoobaSteve** [comment]
So, a possible end goal is to have something as robust like this? https://github.com/typeorm/typeorm,
if so, are you open to PR's?

**Comment by manyuanrong** [comment]
Of course, it would be a good thing to grow as powerful as a typeorm. This is just a starting point, and there is still a lot to do. PR is certainly welcome
