### ISSUE TITLE
Possibility to create an index other than Primary

### ISSUE THREAD

**Issue by Jax-p** [manyuanrong/dso#24]
I would like to be able to create indexes like "UNIQUE, FULLTEXT, INDEX, SPATIAL" not only "PRIMARY".

As long as I think it's not possible at this moment - is there possibility to create custom query from string? Didn't find it neither.

**Comment by tksilicon** [comment]
Hi @Jax-p, I have created #26 to create other indexes. Attn: @manyuanrong.
