### ISSUE TITLE
Could you explain more about example?

### ISSUE THREAD

**Issue by magichim** [manyuanrong/dso#6]
Whenever I follow readme example and execute test.ts code, I got much message like this
```
error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.
```

In dso repo, already exsist tsconfig.json and key, value(experimentalDecorators: true).
however, It's not easy to test. still keep this message on terminal.

What should I do to solve this problem?

**Comment by manyuanrong** [comment]
Deno will not read the tsconfig.json configuration, you need to manually type it at runtime
```sh
deno -A -c tsconfig.json ./test.ts
```
You can find clues in the ci configuration file. Of course, it would be better if there is a more detailed description in the document, I can fill it out if I have enough time, it would be better if someone helps me

**Comment by magichim** [comment]
@manyuanrong Thanks!
